'use client';
import {useState} from 'react';
import {ClientProjectView} from './client-project-view';
import type {Progress,ProjectFile,ProjectMessage} from '@/modules/project-collaboration/queries';
const field='rounded-lg border border-[var(--border)] p-3';
export function CollaborationSandbox({business}:{business:string}){
 const [work,setWork]=useState('Preparing the project brief.');const [next,setNext]=useState('Review the project brief.');
 const [draft,setDraft]=useState<Progress|null>(null);const [published,setPublished]=useState<Progress|null>(null);
 const [shared,setShared]=useState(false);const [messages,setMessages]=useState<ProjectMessage[]>([]);const [notice,setNotice]=useState('');
 const files:ProjectFile[]=[{id:'sample-file',series_id:'sample-file',version:1,name:'Sample project brief',state:'ready',audience:shared?'client':'internal',drive_url:'#practice-collaboration',created_at:'2026-10-07T00:00:00Z'}];
 return <section id="practice-collaboration" className="mt-7 rounded-2xl border border-[var(--border)] p-5"><h2 className="text-xl font-medium">Practice client collaboration</h2><p className="mt-2 text-sm text-[var(--muted)]">Everything here stays in this browser session. No uploads, saved client records, or emails. The sample file illustrates sharing.</p>
 <form className="mt-5 grid gap-3" onSubmit={e=>{e.preventDefault();setDraft({revision:(draft?.revision||0)+1,current_work:work.trim(),next_action:next.trim(),milestones:[{title:'Project brief',status:'in_progress'},{title:'Client review',status:'pending'}]});setNotice('Practice draft saved. Client view stays unchanged until you publish.');}}>
 <label className="grid gap-2 text-sm">Practice current work<textarea required maxLength={5000} value={work} onChange={e=>setWork(e.target.value)} className={field}/></label><label className="grid gap-2 text-sm">Practice client next action<textarea maxLength={5000} value={next} onChange={e=>setNext(e.target.value)} className={field}/></label><button type="submit" className="rounded-lg border border-[var(--border)] p-3 text-sm">Save practice progress draft</button></form>
 <div className="mt-3 flex flex-wrap gap-3"><button type="button" disabled={!draft?.current_work||published?.revision===draft?.revision} onClick={()=>{setPublished(draft);setNotice('Practice progress published. Email delivery remains held.');}} className="rounded-lg border border-[var(--border)] p-3 text-sm disabled:opacity-40">Publish practice progress</button><button type="button" onClick={()=>setShared(value=>!value)} className="rounded-lg border border-[var(--border)] p-3 text-sm">{shared?'Remove sample file from client view':'Share sample file with client'}</button></div>
 <form className="mt-5 grid gap-3" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const body=String(data.get('body')||'').trim();if(!body)return;const audience=data.get('audience')==='client'?'client':'internal';setMessages(items=>[{id:crypto.randomUUID(),author_id:'sample-team',audience,body,created_at:new Date().toISOString()},...items]);e.currentTarget.reset();setNotice(audience==='internal'?'Practice internal note saved. It is absent from the client view.':'Practice client message posted. Email delivery remains held.');}}><label className="grid gap-2 text-sm">Practice message audience<select name="audience" className={field}><option value="internal">Internal note</option><option value="client">Client message</option></select></label><label className="grid gap-2 text-sm">Practice message<textarea required name="body" maxLength={10000} className={field}/></label><button type="submit" className="rounded-lg border border-[var(--border)] p-3 text-sm">Post practice message</button></form>
 {notice?<p role="status" className="mt-3 text-sm">{notice}</p>:null}<div className="mt-4 space-y-2">{messages.filter(m=>m.audience==='internal').map(m=><p key={m.id} className="text-sm text-[var(--muted)]">Internal only: {m.body}</p>)}</div><p className="my-5 text-sm font-medium">Branded client view · published content only</p><ClientProjectView business={business} name="Sample client project" progress={published} files={files} messages={messages}/>
 </section>;
}
