"use client";
import {useState} from "react";
import {onboardingFields,requiredOnboardingKeys,readinessIssues,serviceTemplates,type DeliveryService,type Engagement} from "@/modules/delivery/templates";
export function DeliverySandbox({business}:{business:string}){
 const [service,setService]=useState<DeliveryService>(business==="snd"?"snd":"website");
 const [answers,setAnswers]=useState<Record<string,string>>({});
 const [checks,setChecks]=useState({onboarding_reviewed:false,scope_approved:false,access_ready:false,capacity_ready:false});
 const [submitted,setSubmitted]=useState(false);const [started,setStarted]=useState(false);
 const [paymentEvidence,setPaymentEvidence]=useState("");
 const e:Engagement={id:"sample",service,template_version:2,revision:1,answers,submitted_at:submitted?"sample":null,...checks,payment_required:true,payment_evidence:paymentEvidence,started_at:started?"sample":null,started_by:null};
 const issues=readinessIssues(e);
 function reset(next:DeliveryService){setService(next);setAnswers({});setChecks({onboarding_reviewed:false,scope_approved:false,access_ready:false,capacity_ready:false});setSubmitted(false);setStarted(false);setPaymentEvidence("");}
 return <div className="space-y-6">
  <p role="status" className="rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)] p-4 text-sm">Sample project. Nothing entered here is saved to company records or sent to a client. Refresh to reset.</p>
  <label className="grid max-w-md gap-2 text-sm">Practice service<select value={service} onChange={event=>reset(event.target.value as DeliveryService)} className="rounded-lg border border-[var(--border)] p-3">{Object.entries(serviceTemplates).filter(([key])=>business==="snd"?key==="snd":key!=="snd").map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label>
  <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-medium">Sample onboarding</h2><form onSubmit={event=>{event.preventDefault();setSubmitted(true);}} className="mt-4 grid gap-4 sm:grid-cols-2">{Object.entries(onboardingFields(service,2,answers)).map(([key,label])=><label key={key} className="grid gap-2 text-sm">{label}{key==="branding_included"?<select value={answers[key]||""} onChange={event=>{setAnswers({...answers,[key]:event.target.value});setSubmitted(false);setChecks({...checks,onboarding_reviewed:false});setStarted(false);}} className="rounded-lg border border-[var(--border)] p-3"><option value="">Choose</option><option value="yes">Yes</option><option value="no">No</option></select>:<input type={key==="approver_email"?"email":"text"} name={key} required={key!=="optional_notes"} maxLength={10000} value={answers[key]||""} onChange={event=>{setAnswers({...answers,[key]:event.target.value});setSubmitted(false);setChecks({...checks,onboarding_reviewed:false});setStarted(false);}} className="rounded-lg border border-[var(--border)] p-3"/>}</label>)}<button disabled={requiredOnboardingKeys(service,2,answers).some(key=>!answers[key]?.trim())} type="submit" className="rounded-lg bg-[var(--text)] px-4 py-2 text-sm text-white disabled:opacity-40">Submit sample onboarding</button></form><p className="mt-3 text-sm">{submitted?"Sample onboarding submitted.":"Complete all required fields."}</p></section>
  <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-medium">Sample readiness review</h2><div className="mt-4 space-y-4">{Object.entries({onboarding_reviewed:"Onboarding reviewed",scope_approved:"Scope and terms approved",access_ready:"Required access and dependencies confirmed",capacity_ready:"Team capacity confirmed"}).map(([key,label])=><label key={key} className="flex gap-2 text-sm"><input type="checkbox" checked={checks[key as keyof typeof checks]} disabled={key==="onboarding_reviewed"&&!submitted} onChange={event=>{setChecks({...checks,[key]:event.target.checked});setStarted(false);}}/>{label}</label>)}<label className="grid gap-2 text-sm">Sample payment evidence<input value={paymentEvidence} onChange={event=>{setPaymentEvidence(event.target.value);setStarted(false);}} placeholder="Example receipt reference" className="rounded-lg border border-[var(--border)] p-3"/></label></div>{issues.length?<ul className="mt-4 list-disc space-y-2 pl-5 text-sm">{issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:<p className="mt-4 text-sm">Readiness checks complete.</p>}<button type="button" disabled={issues.length>0||started} onClick={()=>setStarted(true)} className="mt-4 rounded-lg bg-[var(--text)] px-4 py-2 text-sm text-white disabled:opacity-40">Approve sample delivery start</button>{started?<p role="status" className="mt-3 text-sm">Sample delivery started. Live projects require admin approval enforced by the database.</p>:null}</section>
 </div>;
}
