import {randomUUID} from 'node:crypto';
import {ActionForm} from '@/components/action-form';
import {submitPortalRequest} from '@/modules/portal-requests/actions';
import type {PortalRequest} from '@/modules/portal-requests/queries';
export function PortalRequestForm({project,requests}:{project:string;requests:PortalRequest[]}){
 return <section id="requests" className="mt-10 rounded-xl bg-[#f5f0e8] p-6"><h2 className="text-2xl font-semibold">Request a change or report a problem</h2><p className="mt-3">Staff preparation: submissions save to KP. The team reviews your plan before confirming work. No charge or scope change is approved here.</p>
 <ActionForm action={submitPortalRequest} key={requests[0]?.id||'new'} className="mt-5 space-y-4"><input type="hidden" name="project_id" value={project}/><input type="hidden" name="request_id" value={randomUUID()}/><label className="block">Request type<select name="kind" className="mt-2 w-full rounded-lg border p-3"><option value="feature">Feature or change</option><option value="bug">Something broken</option></select></label><label className="block">Short description<input required name="title" maxLength={200} className="mt-2 w-full rounded-lg border p-3"/></label><label className="block">Details<textarea required name="details" maxLength={10000} rows={4} className="mt-2 w-full rounded-lg border p-3"/></label><button className="min-h-11 rounded-lg bg-[#354f8f] px-5 py-3 text-white">Save request to KP</button></ActionForm>
 <h3 className="mt-8 font-semibold">Request history</h3><div className="mt-4 space-y-4">{requests.map(r=><article key={r.id} className="rounded-lg bg-white p-5"><h4 className="font-semibold">{r.title}</h4><p className="mt-2 whitespace-pre-wrap break-words">{r.details}</p><p className="mt-3 text-sm">{r.status} · {r.disposition==='review_included'?'Included work review':r.disposition==='review_quote'?'Quote review':'Plan review needed'}</p>{r.response?<p className="mt-3 whitespace-pre-wrap break-words">Team response: {r.response}</p>:null}</article>)}</div>{!requests.length?<p className="mt-3">No requests yet.</p>:null}</section>;
}
