'use client';
import {useState} from 'react';
import {productionGateLabels,productionStageLabels,stagesForService,type ProductionGate,type ProductionStage} from '@/modules/delivery/production';

export function ProductionSandbox({business}:{business:string}){
 const service=business==='solta'?'website':'snd';const stages=stagesForService(service);
 const [started,setStarted]=useState(false);const [scope,setScope]=useState(false);const [stage,setStage]=useState<ProductionStage|null>(null);
 const [versions,setVersions]=useState({brand_direction:1,copy:1,release:1});
 const empty={brand_direction:false,copy:false,qa:false,launch:false,handoff:false};const [approved,setApproved]=useState(empty);const [clientRelease,setClientRelease]=useState(false);const [message,setMessage]=useState('');
 const gates:ProductionGate[]=business==='solta'?['brand_direction','copy','qa','launch','handoff']:['qa','launch','handoff'];
 function issues(target:ProductionStage){const missing:string[]=[];if(!scope)missing.push('current scope');if(!started)missing.push('delivery start');if(service==='website'&&!approved.brand_direction)missing.push('brand direction');if(service==='website'&&target!=='visual'&&!approved.copy)missing.push('copy');if(['launch','handoff','complete'].includes(target)&&!approved.qa)missing.push('QA');if(['handoff','complete'].includes(target)&&!approved.launch)missing.push('launch approval');if(target==='complete'&&!approved.handoff)missing.push('handoff acceptance');return missing;}
 function approve(kind:ProductionGate){
  if(!started||!scope){setMessage('Approve the sample scope and start delivery first.');return;}
  if(kind==='qa'&&(!stage||stages.indexOf(stage)<stages.indexOf('qa'))){setMessage('Enter QA before recording QA checks.');return;}
  if(kind==='qa'&&issues('qa').length){setMessage(`Resolve: ${issues('qa').join(', ')}.`);return;}
  if(kind==='launch'&&(!approved.qa||!clientRelease||!stage||stages.indexOf(stage)<stages.indexOf('launch'))){setMessage('Enter launch, record QA, and confirm the client approved the sample release version.');return;}
  if(kind==='handoff'&&(!approved.launch||!stage||stages.indexOf(stage)<stages.indexOf('handoff'))){setMessage('Enter handoff and record launch approval first.');return;}
  setApproved(a=>({...a,[kind]:true,...(kind==='brand_direction'||kind==='copy'?{qa:false,launch:false,handoff:false}:kind==='qa'?{launch:false,handoff:false}:kind==='launch'?{handoff:false}:{})}));setMessage(`${productionGateLabels[kind]} recorded for the current sample version.`);
 }
 function move(target:ProductionStage){const previous=stage?stages.indexOf(stage):-1;if(stages.indexOf(target)>previous+1){setMessage('Move one stage at a time.');return;}const missing=issues(target);if(missing.length){setMessage(`Blocked: ${missing.join(', ')}.`);return;}setStage(target);setMessage(`Sample stage: ${productionStageLabels[target]}.`);}
 function revise(kind:'brand_direction'|'copy'|'release'){setVersions(v=>({...v,[kind]:v[kind]+1}));setApproved(a=>({...a,...(kind==='release'?{}:{[kind]:false}),qa:false,launch:false,handoff:false}));if(kind==='release')setClientRelease(false);setMessage('A new version needs fresh approval. Dependent checks reset; the recorded stage remains visible.');}
 const button='rounded-lg border border-[var(--border)] px-3 py-2 text-sm';
 return <section className="mt-7 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-medium">Practice production approvals</h2><p className="mt-2 text-sm text-[var(--muted)]">Sample only. Nothing here saves to KP, records a real approval, publishes work or sends email. Actual projects require approved deliverable versions and evidence.</p><div className="mt-4 flex flex-wrap gap-2"><button className={button} onClick={()=>{setScope(true);setMessage('Sample scope approved.');}}>Approve sample scope</button><button className={button} onClick={()=>{if(!scope){setMessage('Approve sample scope first.');return;}setStarted(true);setMessage('Sample delivery start recorded.');}}>Start sample delivery</button><button className={button} onClick={()=>{setScope(false);setApproved(empty);setMessage('Revised scope resets every sample production approval.');}}>Revise sample scope</button></div><p className="mt-4 text-sm font-medium">Sample stage: {stage?productionStageLabels[stage]:'Delivery preparation'}</p>{stage&&issues(stage).length?<p className="mt-2 text-sm">Renew checks: {issues(stage).join(', ')}.</p>:null}<div className="mt-4 grid gap-3 sm:grid-cols-2">{gates.map(kind=><div key={kind} className="rounded-lg border border-[var(--border)] p-3"><p className="text-sm">{productionGateLabels[kind]} · {approved[kind]?'Approved':'Pending'} · v{kind==='brand_direction'||kind==='copy'?versions[kind]:versions.release}</p><button className={`${button} mt-2`} onClick={()=>approve(kind)}>Approve sample {productionGateLabels[kind].toLowerCase()}</button></div>)}</div><div className="mt-4 flex flex-wrap gap-2">{service==='website'?<><button className={button} onClick={()=>revise('brand_direction')}>Revise sample brand direction</button><button className={button} onClick={()=>revise('copy')}>Revise sample copy</button></>:null}<button className={button} onClick={()=>revise('release')}>Revise sample release</button><button className={button} onClick={()=>{setClientRelease(true);setMessage('Sample client response approved the current release version.');}}>Record sample client release approval</button></div><div className="mt-4 flex flex-wrap gap-2">{stages.map(s=><button key={s} className={button} onClick={()=>move(s)}>Move sample to {productionStageLabels[s]}</button>)}</div>{message?<p role="status" className="mt-4 text-sm">{message}</p>:null}</section>;
}
