import {randomUUID} from 'node:crypto';
import {ActionForm} from '@/components/action-form';
import {recordProductionGate,advanceProduction} from '@/modules/delivery/actions';
import {getProduction} from '@/modules/delivery/queries';
import {getDeliverables} from '@/modules/deliverables/queries';
import {productionGateLabels,productionStageLabels,qaChecks,type ProductionGate,type ProductionStage} from '@/modules/delivery/production';
import type {DeliveryService} from '@/modules/delivery/templates';

export async function ProductionControls({id,business,admin,service}:{id:string;business:string;admin:boolean;service:DeliveryService}){
 const [{state,approvals,events},deliverables]=await Promise.all([getProduction(id),getDeliverables(id)]);
 const applicable:ProductionGate[]=[...(service==='website'||service==='branding'?['brand_direction' as const]:[]),...(service==='website'?['copy' as const]:[]),'qa','launch','handoff'];
 const currentIndex=state.stage?state.stages.indexOf(state.stage):-1;const next=state.stages[currentIndex+1];
 const hidden=<><input type="hidden" name="project_id" value={id}/><input type="hidden" name="business" value={business}/><input type="hidden" name="context" value={state.context}/></>;
 function move(stage:ProductionStage){const issues=state.issues[stage]||[];return <ActionForm key={`${state.context}-${stage}`} action={advanceProduction} errorMessage="This stage could not change. Reload for the latest approvals and readiness checks, then try again." className="mt-3 grid gap-3">{hidden}<input type="hidden" name="request_id" value={randomUUID()}/><input type="hidden" name="stage" value={stage}/><h3 className="text-sm font-medium">Move to {productionStageLabels[stage]}</h3>{issues.length?<ul className="list-disc pl-5 text-sm text-[var(--muted)]">{issues.map(i=><li key={i}>{i}</li>)}</ul>:null}<label className="grid gap-1 text-sm">Reason and evidence<textarea name="evidence" required minLength={5} maxLength={10000} rows={2} className="rounded-lg border border-[var(--border)] p-2"/></label><label className="flex gap-2 text-sm"><input name="confirmed" type="checkbox" required/>I reviewed the current approvals and authorize this stage.</label><label className="grid gap-1 text-sm">Type MOVE {productionStageLabels[stage].toUpperCase()}<input name="confirmation" required autoComplete="off" className="rounded-lg border border-[var(--border)] p-2"/></label><button disabled={issues.length>0} className="rounded-lg bg-[var(--text)] px-4 py-2 text-sm text-white disabled:opacity-40">Confirm stage change</button></ActionForm>;}
 return <section className="mb-7 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5">
  <h2 className="font-medium">Production approvals</h2><p className="mt-2 text-sm text-[var(--muted)]">Start approval prepares the project for production. These separate checks control visual work, build, QA, launch and handoff. Changing a stage here does not publish work, deploy a site or send email.</p>
  <p className="mt-3 text-sm font-medium">Recorded stage: {state.stage?productionStageLabels[state.stage]:'Delivery preparation'}</p>
  {!state.required?<p className="mt-2 text-sm text-[var(--muted)]">Existing work is preserved. Recording a production approval or stage change enables these controls permanently.</p>:null}
  {state.stage&&state.issues[state.stage]?.length?<p role="status" className="mt-3 text-sm">Current stage needs renewed checks: {state.issues[state.stage].join('; ')}. Earlier history is retained.</p>:null}
  <ol className="mt-4 flex flex-wrap gap-2 text-sm">{state.stages.map(s=><li key={s} className="rounded-lg border border-[var(--border)] px-3 py-2" aria-current={s===state.stage?'step':undefined}>{productionStageLabels[s]}</li>)}</ol>
  <div className="mt-5 space-y-4">{applicable.map(kind=>{
   const approved=approvals.find(a=>a.id===state.gates[kind]);
   const expectedKind=kind==='brand_direction'||kind==='copy'?kind:'launch';
   const candidates=deliverables.filter(d=>d.kind===expectedKind).flatMap(d=>d.versions.filter(v=>v.version===d.current_version&&v.reviews.some(r=>r.lane==='internal'&&r.outcome==='approved')&&(kind==='qa'||v.reviews.some(r=>r.lane==='client_record'&&r.outcome==='approved'))).map(v=>({id:v.id,label:`${d.title} · v${v.version}`})));
   return <article key={kind} className="rounded-xl border border-[var(--border)] p-4"><h3 className="text-sm font-medium">{productionGateLabels[kind]} · {approved?'Current approval recorded':'Approval needed'}</h3>{approved?<p className="mt-2 whitespace-pre-wrap break-words text-sm text-[var(--muted)]">{approved.evidence}</p>:null}
    {kind==='brand_direction'?<p className="mt-2 text-sm text-[var(--muted)]">For a website without new branding, record client acceptance of the existing brand direction. Use a Brand direction deliverable below.</p>:null}
    {kind==='qa'?<p className="mt-2 text-sm text-[var(--muted)]">Enter QA first. Check the current release package and record the actual results; exceptions need resolution before approval.</p>:null}
    {kind==='launch'||kind==='handoff'?<p className="mt-2 text-sm text-[var(--muted)]">Use the same Launch / handoff deliverable version as the prior approval. Enter this stage first, then record its separate evidence.</p>:null}
    {admin?<details className="mt-3"><summary className="cursor-pointer text-sm">{approved?'Record a renewed approval':'Record approval'}</summary>{candidates.length?<ActionForm key={`${state.context}-${kind}`} action={recordProductionGate} errorMessage="Approval could not be recorded. Confirm the exact version, required checks and current stage; reload if anything changed." className="mt-3 grid gap-3">{hidden}<input type="hidden" name="request_id" value={randomUUID()}/><input type="hidden" name="kind" value={kind}/><label className="grid gap-1 text-sm">Exact approved package<select name="version_id" required className="rounded-lg border border-[var(--border)] p-2"><option value="">Choose a version</option>{candidates.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label>{kind==='qa'?qaChecks.map((check,i)=><label key={check} className="flex gap-2 text-sm"><input type="checkbox" required name={`qa_${i}`}/>{check}</label>):null}<label className="grid gap-1 text-sm">Actual approval or check evidence<textarea name="evidence" required minLength={5} maxLength={9000} rows={3} placeholder="Results, approver or handoff recipient, date and evidence reference. Never credentials." className="rounded-lg border border-[var(--border)] p-2"/></label><label className="flex gap-2 text-sm"><input name="confirmed" type="checkbox" required/>This evidence applies to the exact current version and scope.</label><label className="grid gap-1 text-sm">Type APPROVE {productionGateLabels[kind].toUpperCase()}<input name="confirmation" required autoComplete="off" className="rounded-lg border border-[var(--border)] p-2"/></label><button className="rounded-lg border border-[var(--border)] px-4 py-2 text-sm">Record {productionGateLabels[kind].toLowerCase()}</button></ActionForm>:<p className="mt-3 text-sm text-[var(--muted)]">Create a {expectedKind==='launch'?'Launch / handoff':productionGateLabels[kind]} deliverable below. Its current version needs internal approval{kind==='qa'?'':' and an evidenced client approval'}.</p>}</details>:null}
   </article>;
  })}</div>
  {admin&&next?<div className="mt-5 rounded-xl border border-[var(--border)] p-4">{move(next)}</div>:null}
  {admin&&currentIndex>=0?<details className="mt-5"><summary className="cursor-pointer text-sm">Revisit a stage or renew the recorded stage</summary><p className="mt-2 text-sm text-[var(--muted)]">Earlier stages can be revisited for corrections. Forward steps still require fresh applicable approvals.</p><div className="grid gap-5">{state.stages.slice(0,currentIndex+1).map(move)}</div></details>:null}
  {!admin?<p className="mt-5 text-sm text-[var(--muted)]">Admin records production authority. Assigned reviewers can still review deliverable versions below.</p>:null}
  {approvals.length||events.length?<details className="mt-5"><summary className="cursor-pointer text-sm">Production history</summary><div className="mt-3 space-y-3">{events.map(e=><p key={e.id} className="whitespace-pre-wrap break-words text-sm">Stage #{e.sequence} · {productionStageLabels[e.stage]} · {e.actor?.display_name||'Staff'} · {new Date(e.recorded_at).toLocaleDateString('en-US',{timeZone:'UTC'})}: {e.evidence}</p>)}{approvals.map(a=><p key={a.id} className="whitespace-pre-wrap break-words text-sm">{productionGateLabels[a.kind]} approval #{a.revision} · {state.gates[a.kind]===a.id?'Current':'Historical; not current approval'} · {a.actor?.display_name||'Staff'} · {new Date(a.recorded_at).toLocaleDateString('en-US',{timeZone:'UTC'})}: {a.evidence}</p>)}</div></details>:null}
 </section>;
}
