import {randomUUID} from "node:crypto";
import {ActionForm} from "@/components/action-form";
import {saveScope,approveScope} from "@/modules/delivery/actions";
import {getScopes} from "@/modules/delivery/queries";

export async function ProjectScope({id,business,admin,required}:{id:string;business:string;admin:boolean;required:boolean}){
 const {versions,approvals}=await getScopes(id);const current=versions[0];const approval=approvals.find(a=>a.scope_id===current?.id);
 const fields={deliverables:"Deliverables and acceptance criteria",exclusions:"Exclusions and client responsibilities",commercial_terms:"Price, payment schedule and commercial terms",timing:"Timing, dependencies and revision limits"} as const;
 const hidden=<><input type="hidden" name="project_id" value={id}/><input type="hidden" name="business" value={business}/></>;
 return <section className="mb-7 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5">
  <h2 className="font-medium">Scope & terms</h2>
  <p className="mt-2 text-sm text-[var(--muted)]">Every saved version is retained. Record a real client approval of the current version before starting delivery. Changes require fresh approval. Client sign-in comes later; staff record the response received by email or another agreed channel.</p>
  {!required&&!current?<p className="mt-3 text-sm">Existing start approval preserved. Saving a scope version enables the new approval requirement.</p>:null}
  {current?<div className="mt-4 space-y-3"><p className="font-medium">Current scope · v{current.version} · {approval?"Approved":"Awaiting client approval"}</p>{Object.entries(fields).map(([key,label])=><div key={key}><h3 className="text-sm font-medium">{label}</h3><p className="mt-1 whitespace-pre-wrap break-words text-sm text-[var(--muted)]">{current[key as keyof typeof fields]}</p></div>)}<p className="text-sm">Reason: {current.change_reason}</p>{approval?<div className="rounded-lg border border-[var(--border)] p-3 text-sm"><p>Client approval recorded for v{current.version}: {approval.client_name} ({approval.client_email})</p><p className="mt-2 whitespace-pre-wrap break-words">{approval.evidence}</p></div>:null}</div>:<p className="mt-4 text-sm">No version saved yet.</p>}
  {admin&&current&&!approval?<ActionForm key={`approve-${current.id}`} action={approveScope} className="mt-5 grid gap-3">{hidden}<input type="hidden" name="scope_id" value={current.id}/><h3 className="text-sm font-medium">Record client approval of v{current.version}</h3><label className="grid gap-1 text-sm">Client approver name<input name="client_name" required maxLength={200} className="rounded-lg border border-[var(--border)] p-2"/></label><label className="grid gap-1 text-sm">Client approver email<input name="client_email" type="email" required maxLength={320} className="rounded-lg border border-[var(--border)] p-2"/></label><label className="grid gap-1 text-sm">Approval evidence<textarea name="evidence" required minLength={5} maxLength={10000} rows={3} placeholder="Actual client response, date, and email or document reference" className="rounded-lg border border-[var(--border)] p-2"/></label><label className="flex gap-2 text-sm"><input type="checkbox" name="client_confirmed" required/>The client approved this exact scope version.</label><label className="grid gap-1 text-sm">Type APPROVE v{current.version}<input name="confirmation" required autoComplete="off" className="rounded-lg border border-[var(--border)] p-2"/></label><button className="rounded-lg bg-[var(--text)] px-4 py-2 text-sm text-white">Record approval</button></ActionForm>:null}
  {admin?<details className="mt-5"><summary className="cursor-pointer text-sm font-medium">{current?"Prepare a revised scope":"Prepare initial scope"}</summary><ActionForm key={`scope-${current?.id||'initial'}`} action={saveScope} className="mt-4 grid gap-3">{hidden}<input type="hidden" name="request_id" value={randomUUID()}/><input type="hidden" name="expected_version" value={current?.version||0}/>{Object.entries(fields).map(([key,label])=><label key={key} className="grid gap-1 text-sm">{label}<textarea name={key} defaultValue={current?.[key as keyof typeof fields]||""} required minLength={5} maxLength={10000} rows={3} className="rounded-lg border border-[var(--border)] p-2"/></label>)}<label className="grid gap-1 text-sm">Reason for this version<textarea name="change_reason" required minLength={5} maxLength={2000} rows={2} className="rounded-lg border border-[var(--border)] p-2"/></label><p className="text-sm text-[var(--muted)]">Saving creates v{(current?.version||0)+1}. Earlier approval will stay in history and will not approve this version.</p><button className="rounded-lg border border-[var(--border)] px-4 py-2 text-sm">Save scope version</button></ActionForm></details>:<p className="mt-4 text-sm text-[var(--muted)]">Admin prepares scope and records approval evidence.</p>}
  {versions.length>1?<details className="mt-5"><summary className="cursor-pointer text-sm">Earlier scope versions ({versions.length-1})</summary>{versions.slice(1).map(v=><article key={v.id} className="mt-3 space-y-2 rounded-lg border border-[var(--border)] p-3 text-sm"><p className="font-medium">v{v.version} · {approvals.some(a=>a.scope_id===v.id)?"Approval retained; superseded":"Superseded without approval"}</p>{Object.entries(fields).map(([key,label])=><p key={key} className="whitespace-pre-wrap break-words"><strong>{label}:</strong> {v[key as keyof typeof fields]}</p>)}<p>Reason: {v.change_reason}</p>{approvals.filter(a=>a.scope_id===v.id).map(a=><p key={a.scope_id} className="whitespace-pre-wrap break-words">Approval: {a.client_name} ({a.client_email}) — {a.evidence}</p>)}</article>)}</details>:null}
 </section>;
}
