import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {ActionForm} from '@/components/action-form';
import {ProgressEditor} from './progress-editor';
import {getProjectCollaboration} from '@/modules/project-collaboration/queries';
import {addProjectFile,postProjectMessage,publishProjectProgress,setProjectFileAudience} from '@/modules/project-collaboration/actions';
const box='mb-7 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5';
const field='rounded-lg border border-[var(--border)] p-3';
const button='rounded-lg bg-[var(--text)] px-4 py-2 text-sm text-white';
export async function ProjectCollaboration({id,business}:{id:string;business:string}){
 const data=await getProjectCollaboration(id);
 function context(){return <><input type="hidden" name="id" value={id}/><input type="hidden" name="business" value={business}/></>;}
 return <>
 <section className={box}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-medium">Client progress</h2><Link href={`/client-preview/${business}/projects/${id}`} className="text-sm underline">Preview client view</Link></div><p className="mt-2 text-sm text-[var(--muted)]">Save privately, then publish when ready. Project stage changes never publish an update.</p><ProgressEditor key={data.draft?.revision||0} id={id} business={business} draft={data.draft}/>{data.draft?<ActionForm action={publishProjectProgress} className="mt-4">{context()}<input type="hidden" name="revision" value={data.draft.revision}/><button type="submit" disabled={!data.draft.current_work.trim()||data.published?.draft_revision===data.draft.revision} className={`${button} disabled:opacity-40`}>Publish saved progress</button></ActionForm>:null}<p className="mt-3 text-sm text-[var(--muted)]">{data.published?'A published update is available in the client preview.':'Nothing published yet.'}</p></section>
 <section className={box}><h2 className="font-medium">Files & versions</h2><p className="mt-2 text-sm text-[var(--muted)]">Uploads are private. Each new version is retained. Share a ready file explicitly to include it in the client view. Drive links keep their existing Drive permissions.</p>
 <ActionForm action={addProjectFile} key={`upload-${data.files.length}`} className="mt-4 grid gap-3">{context()}<input type="hidden" name="request_id" value={randomUUID()}/><input type="hidden" name="source" value="upload"/><label className="grid gap-2 text-sm">Upload file · up to 20 MB<input required type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.csv" className={field}/></label><label className="grid gap-2 text-sm">File version<select name="series_id" className={field}><option value="">New file</option>{data.files.filter((f,i,all)=>all.findIndex(item=>item.series_id===f.series_id)===i).map(f=><option key={f.series_id} value={f.series_id}>New version of {f.name}</option>)}</select></label><button type="submit" className={button}>Upload private file</button></ActionForm>
 <ActionForm action={addProjectFile} key={`drive-${data.files.length}`} className="mt-5 grid gap-3">{context()}<input type="hidden" name="request_id" value={randomUUID()}/><input type="hidden" name="source" value="drive"/><label className="grid gap-2 text-sm">Drive file name<input required name="name" maxLength={200} className={field}/></label><label className="grid gap-2 text-sm">Google Drive or Docs link<input required type="url" name="drive_url" className={field}/></label><button type="submit" className={button}>Add private Drive link</button></ActionForm>
 <ul className="mt-5 space-y-4">{data.files.map(f=><li key={f.id} className="rounded-lg border border-[var(--border)] p-3"><p className="text-sm">{f.state==='ready'?<a href={f.drive_url||`/api/v1/project-files/${f.id}`} target={f.drive_url?'_blank':undefined} rel="noreferrer" className="underline">{f.name}</a>:f.name} · Version {f.version} · {f.state==='pending'?'Upload pending':f.audience==='client'?'Shared with client':'Internal only'}</p>{f.state==='ready'?<ActionForm action={setProjectFileAudience} className="mt-3">{context()}<input type="hidden" name="file_id" value={f.id}/><input type="hidden" name="audience" value={f.audience==='client'?'internal':'client'}/><button type="submit" className="text-sm underline">{f.audience==='client'?'Remove from client view':'Share with client'}</button></ActionForm>:null}</li>)}</ul></section>
 <section className={box}><h2 className="font-medium">Messages & internal notes</h2><ActionForm action={postProjectMessage} key={`message-${data.messages[0]?.id||'empty'}`} className="mt-4 grid gap-3">{context()}<input type="hidden" name="request_id" value={randomUUID()}/><label className="grid gap-2 text-sm">Audience<select name="audience" className={field}><option value="internal">Internal note</option><option value="client">Client message</option></select></label><label className="grid gap-2 text-sm">Message<textarea required name="body" maxLength={10000} rows={3} className={field}/></label><button type="submit" className={button}>Post message</button></ActionForm><p className="mt-3 text-sm text-[var(--muted)]">Client messages appear in the preview. Email delivery is held until verified client access is enabled. {data.heldNotifications} notification{data.heldNotifications===1?'':'s'} held.</p><div className="mt-5 space-y-3">{data.messages.map(m=><article key={m.id} className="rounded-lg border border-[var(--border)] p-3"><p className="text-xs text-[var(--muted)]">{m.audience==='client'?'Client message':'Internal note'} · {m.author?.display_name||'Team member'} · {new Date(m.created_at).toLocaleDateString('en-US',{timeZone:'UTC'})}</p><p className="mt-2 whitespace-pre-wrap text-sm">{m.body}</p></article>)}</div></section>
 </>;
}
