import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';const {PGlite}=await import(process.env.PGLITE_TEST_PACKAGE||'@electric-sql/pglite');const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create schema private;create schema storage;grant usage on schema auth,private,storage,public to authenticated;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table profiles(id uuid primary key,role text,status text);create table knowledge_documents(id uuid primary key);
create function private.is_active_member() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and status='active')$$;
create function private.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and status='active' and role='admin')$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant select,insert on storage.objects to authenticated;
insert into profiles values('00000000-0000-4000-8000-000000000001','admin','active'),('00000000-0000-4000-8000-000000000002','team_member','active'),('00000000-0000-4000-8000-000000000003','team_member','disabled');insert into knowledge_documents values('10000000-0000-4000-8000-000000000001');`);
await db.exec(await readFile(new URL('../../supabase/migrations/20261008000754_library_brand_assets.sql',import.meta.url),'utf8'));
async function user(n){await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-00000000000${n}',false)`);}
const id='20000000-0000-4000-8000-000000000001',doc='10000000-0000-4000-8000-000000000001',path=`${doc}/${id}/guide.pdf`;
await user(2);await assert.rejects(db.query("insert into library_files(id,document_id,name,object_path,mime_type,size_bytes,sha256,created_by) values($1,$2,'guide.pdf',$3,'application/pdf',10,$4,auth.uid())",[id,doc,path,'a'.repeat(64)]),/Admin|row-level/);
await user(1);await db.query("insert into library_files(id,document_id,name,object_path,mime_type,size_bytes,sha256,created_by) values($1,$2,'guide.pdf',$3,'application/pdf',10,$4,auth.uid())",[id,doc,path,'a'.repeat(64)]);await assert.rejects(db.query("update library_files set state='ready' where id=$1",[id]),/Upload not complete/);
await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('kp-library-files','unreserved.pdf')"),/row-level/);await db.query("insert into storage.objects(bucket_id,name) values('kp-library-files',$1)",[path]);await db.query("update library_files set state='ready' where id=$1",[id]);await assert.rejects(db.query("update library_files set name='changed.pdf' where id=$1",[id]),/immutable/);
await user(2);assert.equal((await db.query('select * from library_files')).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows.length,1);await assert.rejects(db.query('delete from library_files where id=$1',[id]),/permission denied/);
await user(3);assert.equal((await db.query('select * from library_files')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);await db.exec('reset role;set role anon');await assert.rejects(db.query('select * from library_files'),/permission denied/);await db.close();console.log('Library-file checks passed: admin reservations/uploads, private staff reads, upload completion, immutable originals and disabled/anonymous denial.');
