import {randomUUID} from 'node:crypto';
import {requireAdminIdentity} from '@/lib/auth/current-user';
import {createClient} from '@/lib/supabase/server';
import {PageHeading} from '@/components/page-heading';
import {ActionForm} from '@/components/action-form';
import {TeamMemberEditor} from '@/components/team-member-editor';
import {prepareStaff,cancelStaffPreparation} from '@/modules/team/actions';
import type {StaffMember} from '@/modules/team/types';
export default async function TeamPage(){
 const {profile}=await requireAdminIdentity();const db=await createClient();
 const [roster,invitations,events]=await Promise.all([db.rpc('kp_team_roster'),db.from('staff_invitations').select('id,email,display_name,state,created_at').order('created_at',{ascending:false}).limit(100),db.from('team_admin_events').select('id,actor_id,profile_id,action,reason,created_at').order('created_at',{ascending:false}).limit(30)]);
 for(const result of [roster,invitations,events])if(result.error)throw new Error(result.error.message);
 const members=(roster.data||[]) as StaffMember[];const names=new Map(members.map(m=>[m.id,m.display_name||m.email]));const field='rounded-lg border border-[var(--border)] p-3';
 return <><PageHeading eyebrow="Admin" title="Team & access" description="Manage staff roles and active access. Work and history stay with the company when someone leaves."/>
 <p className="mb-5 text-sm text-[var(--muted)]">Staff share company work across Solta and Sent. Use staff access only for your internal team. Client portal logins will have separate access when client authentication is added.</p>
 <section className="mb-6 rounded-2xl border border-[var(--border)] p-5"><h2 className="font-medium">Prepare a new staff member</h2><p className="mt-2 text-sm text-[var(--muted)]">Prepare the approved email and name. This saves a staff entry; it does not send an invitation or grant access. A login must be created and verified, then activated by an admin. Invitation delivery will be connected in the authentication slice.</p>
 <ActionForm action={prepareStaff} className="mt-4 grid gap-3 sm:grid-cols-2" errorMessage="Couldn’t prepare this staff entry. Check the email and name; an existing staff entry must be managed in the roster."><input type="hidden" name="id" value={randomUUID()}/><label className="grid gap-2 text-sm">Staff name<input name="name" required maxLength={120} className={field}/></label><label className="grid gap-2 text-sm">Staff email<input name="email" type="email" required maxLength={254} className={field}/></label><label className="grid gap-2 text-sm sm:col-span-2">Why add this person?<textarea name="reason" required minLength={5} maxLength={2000} className={field}/></label><button className={field}>Prepare staff entry</button></ActionForm></section>
 <h2 className="mb-3 font-medium">Staff roster</h2><div className="space-y-3">{members.map(member=><article key={`${member.id}:${member.revision}`} className="rounded-xl border border-[var(--border)] p-5"><h3 className="font-medium">{member.display_name||member.email}{member.id===profile.id?' · you':''}</h3><p className="mt-1 text-sm text-[var(--muted)]">{member.email} · {member.role==='admin'?'Admin':'Team member'} · {member.status==='active'?'Active':'Disabled / awaiting activation'}</p><p className="mt-2 text-xs text-[var(--muted)]">{member.confirmed?'Email confirmed':'Email confirmation pending'} · {member.open_tasks} unfinished tasks · {member.open_projects} open projects</p><TeamMemberEditor member={member} self={member.id===profile.id}/></article>)}</div>
 <h2 className="mb-3 mt-7 font-medium">Staff preparations</h2><div className="space-y-3">{invitations.data?.map(invitation=><article key={invitation.id} className="rounded-xl border border-[var(--border)] p-4"><h3 className="text-sm font-medium">{invitation.display_name} · {invitation.email}</h3><p className="mt-1 text-sm text-[var(--muted)]">{invitation.state==='linked'?'Login linked; manage access in the roster':invitation.state==='cancelled'?'Cancelled; retained in history':'Prepared; invitation not sent'}</p>{invitation.state==='prepared'?<details className="mt-3"><summary className="cursor-pointer text-sm">Cancel this preparation</summary><ActionForm action={cancelStaffPreparation} className="mt-3 grid gap-3" errorMessage="Couldn’t cancel. Check the exact email; linked logins must be managed in the roster."><input type="hidden" name="id" value={invitation.id}/><label className="grid gap-2 text-sm">Reason<input name="reason" required minLength={5} maxLength={2000} className={field}/></label><label className="grid gap-2 text-sm">Type exactly: CANCEL {invitation.email}<input name="confirmation" required className={field}/></label><label className="flex gap-2 text-sm"><input name="verified" type="checkbox" required/>I verified this staff preparation.</label><button className={field}>Cancel staff preparation</button></ActionForm></details>:null}</article>)}</div>{!invitations.data?.length?<p className="text-sm text-[var(--muted)]">No staff preparations yet.</p>:null}
 <h2 className="mb-3 mt-7 font-medium">Recent access history</h2><div className="space-y-3">{events.data?.map(event=><article key={event.id} className="rounded-xl border border-[var(--border)] p-4 text-sm"><p>{event.action.replaceAll('_',' ')} · {names.get(event.actor_id)||'Previous admin'}</p><p className="mt-1 text-[var(--muted)]">{event.reason}</p><time className="mt-2 block text-xs text-[var(--muted)]">{new Date(event.created_at).toISOString()}</time></article>)}</div>{!events.data?.length?<p className="text-sm text-[var(--muted)]">Access changes will appear here.</p>:null}</>;
}
