import Link from 'next/link';
import {ActionForm} from '@/components/action-form';
import {requireActiveIdentity} from '@/lib/auth/current-user';
import {getPortalRequests} from '@/modules/portal-requests/queries';
import {reviewPortalRequest} from '@/modules/portal-requests/actions';
export default async function RequestQueue(){
 const {profile}=await requireActiveIdentity();const requests=await getPortalRequests();
 return <><h1 className="text-3xl font-semibold">Solta client requests</h1><p className="mt-3">Staff preparation queue · Latest 100 submissions. These are separate from internal KP feature requests. Reviews do not approve charges or change delivery scope.</p><div className="mt-6 space-y-6">{requests.map(r=><article key={`${r.id}-${r.revision}`} className="rounded-xl border p-5"><Link className="underline" href={`/businesses/solta/projects/${r.project_id}`}>Open project</Link><h2 className="mt-3 text-xl font-semibold">{r.title}</h2><p className="mt-2 whitespace-pre-wrap break-words">{r.details}</p><p className="mt-3">{r.kind==='bug'?'Bug report':'Feature request'} · {r.status} · {r.disposition==='review_included'?'Included work review':r.disposition==='review_quote'?'Quote review':'Plan review needed'} · Policy v{r.policy_revision}</p>{profile.role==='admin'?<ActionForm action={reviewPortalRequest} errorMessage="Couldn’t save the review. Explain the outcome or reload if the request changed." className="mt-4 space-y-4"><input type="hidden" name="id" value={r.id}/><input type="hidden" name="revision" value={r.revision}/><label className="block">Review status<select name="status" defaultValue={r.status} className="ml-3 rounded-lg border p-2">{['submitted','reviewing','waiting','resolved','declined'].map(s=><option key={s}>{s}</option>)}</select></label><label className="block">Response<textarea name="response" defaultValue={r.response} rows={3} maxLength={10000} className="mt-2 w-full rounded-lg border p-3"/></label><button className="rounded-lg bg-[var(--text)] px-4 py-2 text-white">Save review</button></ActionForm>:<p className="mt-3">{r.response||'Awaiting admin review.'}</p>}</article>)}</div>{!requests.length?<p className="mt-5">No client requests yet.</p>:null}</>;
}
