'use client';
import {useState} from 'react';
import {ActionForm} from './action-form';
import {archiveRecord} from '@/modules/archive/actions';
export function ArchiveRecord({id,name,type,restoring=false}:{id:string;name:string;type:string;restoring?:boolean}){
 const [open,setOpen]=useState(false);const [confirmation,setConfirmation]=useState('');const [reason,setReason]=useState('');const [verified,setVerified]=useState(false);
 const operation=restoring?'restore':'archive';const phrase=`${operation.toUpperCase()} ${name}`;
 if(!open)return <button type="button" className="mt-3 rounded-lg border border-[var(--border)] px-3 py-2 text-xs" onClick={()=>setOpen(true)}>{restoring?'Restore':'Remove safely'} · {name}</button>;
 return <div className="mt-3 rounded-xl border border-[var(--border)] p-4"><h3 className="font-medium">{restoring?'Restore':'Archive'} {name}?</h3><p className="mt-2 text-sm text-[var(--muted)]">{restoring?'Returns this record to normal views. Existing history is preserved.':'Hides this record from normal views. It remains recoverable here; related history is retained. A company with active linked work or contacts cannot be archived until those links are handled.'}</p>
 <ActionForm action={archiveRecord} className="mt-3 grid gap-3" errorMessage="Couldn’t change this record. Check the exact confirmation; companies with active linked records must be handled first."><input type="hidden" name="entity_type" value={type}/><input type="hidden" name="entity_id" value={id}/><input type="hidden" name="operation" value={operation}/><label className="grid gap-2 text-sm">Reason for {operation}<textarea required name="reason" value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={2000} className="rounded-lg border border-[var(--border)] p-3"/></label><label className="grid gap-2 text-sm">Type exactly: {phrase}<input required name="confirmation" value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off" className="rounded-lg border border-[var(--border)] p-3"/></label><label className="flex gap-2 text-sm"><input required type="checkbox" name="verified" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I verified the record and understand this action.</label><button disabled={confirmation!==phrase||reason.trim().length<5||!verified} className="rounded-lg bg-[var(--text)] px-4 py-2 text-sm text-white disabled:opacity-40">Confirm {operation}</button></ActionForm><button type="button" className="mt-3 text-sm underline" onClick={()=>{setOpen(false);setConfirmation('');setReason('');setVerified(false);}}>Cancel</button></div>;
}
