'use client';
import {useRef,useState} from 'react';
import {previewLeadImport,commitLeadImport} from '@/modules/lead-imports/actions';
import type {LeadRow} from '@/modules/lead-imports/normalize';
export function LeadImporter({business}:{business:string}){
 const [rows,setRows]=useState<LeadRow[]>([]);const [fileName,setFileName]=useState('');const [excluded,setExcluded]=useState<number[]>([]);const [receipt,setReceipt]=useState<{added:number;skipped:number}|null>(null);const [confirmed,setConfirmed]=useState(false);const [pending,setPending]=useState(false);const [error,setError]=useState('');const request=useRef('');const lock=useRef(false);
 const selected=rows.filter(row=>!excluded.includes(row.row));
 const blocked=selected.some(row=>row.issue||(row.suggested&&row.suggested!==row.business&&row.override_reason.trim().length<5));
 const field='rounded-lg border border-[var(--border)] p-2 text-sm';
 return <section className="mb-7 rounded-2xl border border-[var(--border)] p-5"><h2 className="font-medium">Import sourced leads</h2><p className="mt-2 text-sm text-[var(--muted)]">Upload Google Sheets exported as CSV or Excel (.xlsx), up to 500 leads / 2 MB. Include Company, Website, Email, Contact, Service, Source, Source URL and Notes as available. Website/branding work suggests Solta; lifecycle/email marketing suggests Sent. Review the destination before saving. No outreach is sent.</p>
 <form className="mt-4 flex flex-wrap gap-3" onSubmit={async e=>{e.preventDefault();if(lock.current)return;lock.current=true;setPending(true);setError('');const form=new FormData(e.currentTarget);try{const preview=await previewLeadImport(form);setRows(preview.rows);setFileName(preview.fileName);setExcluded(preview.rows.filter(row=>row.issue).map(row=>row.row));setConfirmed(false);setReceipt(null);request.current=crypto.randomUUID();}catch(e){setError(e instanceof Error?e.message:'Could not preview this file.');}finally{setPending(false);lock.current=false;}}}><input type="hidden" name="business" value={business}/><label className="grid gap-2 text-sm">Lead spreadsheet<input required name="file" type="file" accept=".csv,.xlsx" disabled={pending}/></label><button disabled={pending} className={field}>Preview leads</button></form>
 {rows.length&&!receipt?<><p className="my-4 text-sm">{fileName} · {selected.length} selected · {rows.length-selected.length} excluded. Existing matching leads will be skipped; existing contacts are never overwritten.</p><div className="max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Import</th><th>Company / source</th><th>Service</th><th>Destination</th><th>Review</th></tr></thead><tbody>{rows.map(row=><tr key={row.row} className="border-t border-[var(--border)]"><td className="p-2"><input aria-label={`Include row ${row.row}`} type="checkbox" disabled={!!row.issue||pending} checked={!excluded.includes(row.row)} onChange={e=>{setExcluded(items=>e.target.checked?items.filter(n=>n!==row.row):[...items,row.row]);setConfirmed(false);}}/></td><td className="p-2">{row.company}<p className="text-xs text-[var(--muted)]">{row.website||row.email}<br/>{row.source}</p></td><td className="p-2">{row.service||'Not specified'}</td><td className="p-2"><select aria-label={`Business for row ${row.row}`} value={row.business} disabled={pending} onChange={e=>{setRows(items=>items.map(item=>item.row===row.row?{...item,business:e.target.value as LeadRow['business']}:item));setConfirmed(false);}} className={field}><option value="solta">Solta</option><option value="snd">Sent & Delivered</option></select></td><td className="p-2">{row.issue|| (row.suggested?`Service suggests ${row.suggested==='solta'?'Solta':'Sent'}`:'Uses selected business; check fit')}{row.suggested&&row.suggested!==row.business?<label className="grid gap-2">Why override row {row.row}?<input value={row.override_reason} disabled={pending} minLength={5} maxLength={2000} className={field} onChange={e=>{setRows(items=>items.map(item=>item.row===row.row?{...item,override_reason:e.target.value}:item));setConfirmed(false);}}/></label>:null}</td></tr>)}</tbody></table></div><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" disabled={pending} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed these leads and their destination businesses.</label><button disabled={!confirmed||!selected.length||blocked||pending} className={`${field} mt-3 disabled:opacity-40`} onClick={async()=>{if(lock.current)return;lock.current=true;setPending(true);setError('');try{setReceipt(await commitLeadImport(request.current,fileName,selected));}catch(e){setError(e instanceof Error?e.message:'Import failed; retry keeps the same request receipt.');}finally{setPending(false);lock.current=false;}}}>Import {selected.length} reviewed leads</button></>:null}
 {receipt?<p role="status" className="mt-4 text-sm">Imported {receipt.added} leads. Skipped {receipt.skipped} existing matches. No messages were sent.</p>:null}{error?<p role="alert" className="mt-4 text-sm">{error}</p>:null}
 </section>;
}
